### PR TITLE
Ability to use another Card Emulator

### PR DESCRIPTION
**Pull request by leezhiwei**
Hi @BroGamer4256, have seen the code done by @GXTX previously in #9, I have attempted to re-implement, and made new options in `config.toml`, as well as the ability to hook onto any Serial device. Let me know if there is anything to change. Thanks!

### CODE REVIEW

**Comment by GXTX** [comment]
Reason for the close?

**Comment by BroGamer4256** [comment]
Failure to properly format code, interferes with other functions of the game, horribly messy code, no particular reason for this to be implemented in the first place.

**Comment by leezhiwei** [comment]
Okay @BroGamer4256, it is quite a useful feature see, what if someone wants to use an external card emu, which your card emu does not provide (external Web UI, for another set of displays, and multiple card management), unless you are planning to implement these features.


Also again with the **Spaghetti code**, as well as interference of functions. I have tried to do the following.
1. Try and do as much documentation with comments.
2. Try and split out each variable into readable names.
3. Make this feature enable/disable-able using config.toml
4. Even in config.toml it is disabled by default. I have tested it, your inbuilt card_emu works!!!

So I just don't get it. Thanks.

**Comment by leezhiwei** [comment]
If you give me a part of your code that is considered as 'clean', do let me know.

**Comment by leezhiwei** [comment]
Also, I tried my best to account for interference, look at `lib.rs`, I have set it to `panic!` once it detects when the user tries to redirect the card, and enables your card_emu, I tried my darnest to account for odd situations.

**Comment by BroGamer4256** [comment]
From  your comment its very clear to me that you have not actually looked at this code in a reverse engineering program, the function that is being hooked is used for far more than just cards which anyone would be able to see in 2 seconds. By forcing this function to always return the open card port it'd break the other serial interfaces opened with this function. This can even be observed by looking at the functions name.

**Comment by realgorgan** [comment]
This feature is greatly appreciated and I feel would be extremely beneficial for this repository. Opening up the loader to other card emus opens up other possibilities and more features (as stated by Lee). This repository has only been made better by the community and will continue to do so. The more features the community implements, the less work for you @BroGamer4256 !!
The code isn’t messy by any means. I’d say it’s very good from a programming aspect. It’s well documented with comments etc….

**Comment by BroGamer4256** [comment]
Its some of the worst quality code I've ever had the displeasure of reading

**Comment by leezhiwei** [comment]
> From  your comment its very clear to me that you have not actually looked at this code in a reverse engineering program, the function that is being hooked is used for far more than just cards which anyone would be able to see in 2 seconds. By forcing this function to always return the open card port it'd break the other serial interfaces opened with this function. This can even be observed by looking at the functions name.

Okay actually **useful** feedback. Sure, do you have a Ghidra project file that I can tinker with, or *another* function I can hook onto?

**Comment by GXTX** [comment]
To answer above ^. It's also used for FFB, which is another thing that having 3rd party application support would be useful for.

**Comment by BroGamer4256** [comment]
Hooking this function is arguably the worst possible to implement this idea. You should identify the actual reason why you cannot do something you want and then work from there.

**Comment by leezhiwei** [comment]
Hi, the main reason why this function has been function as been `chosen` is that this allows the game to open the serial port to read, using a [file descriptor](https://en.m.wikipedia.org/wiki/File_descriptor), which allows for piping software such as `socat` to work, running the other card emulator locally (since I highly doubt anyone has a real serial port anymore). To try and mitigate your concerns, I can do some handling (only intercept calls to `/dev/ttyM2` (the card reader)), if it tries to talk to other serial devices, I will try and open that instead.

**Comment by BroGamer4256** [comment]
Seems like you don't fully understand what I mean, that can all be done without hooking this specific function.

**Comment by leezhiwei** [comment]
Okay cool, can you *suggest* another function to hook onto? I'll take a look at the function you suggest using Ghidra.

**Comment by GXTX** [comment]
> Its some of the worst quality code I've ever had the displeasure of reading. [...] Rust has a very standardized format that this blatantly ignores.

It appears to be essentially 1:1 with what I originally wrote sans supporting the FFB port. We've discussed this before, first time touching the language, and I simply worked backwards from what the compiler was complaining about. It's valid code, and it works.

> You should always run cargo fmt on rust code to match this standard.

Perhaps a suggestion you should put on some ML where by the compiler will warn for this. 

> Hooking this function is arguably the worst possible way to implement this idea. You should identify what is blocking you from using arbitrary serial devices and then work from there.

From what I remember, and it's been a little so remind me where I am wrong; This function essentially gets passed an int (`portno`) which is inside of a struct. The function then attempts to open an fd with named `/dev/ttyMX` where **X** is replaced by `portno`, and with specific, non-editable, flags (`O_RDWR | O_NOCTTY | O_NONBLOCK`). It then attempts to set real RS232 port settings (can't remember the fd args off the top of my head), this is where the real hangup is. Pipes and the like will fail setting port settings, as expected, because they are not real RS232 ports. Hence, this and my original PR attempting to simply take control over port opening. Additionally, for reasons I can no longer articulate, I needed to add `O_SYNC` to the flags.

If you want fallback behavior it's something you should probably suggest instead of saying "this is wrong", "this is AI", "do it somewhere else", and being overly hostile. You are, unironically, the exact reason why I dislike *actually* attempting to upstream code changes to open source projects.

**Comment by realgorgan** [comment]
I feel like at this point, we should just fork and make a better version of this loader and just tell people “if you want features without the hostility of the original creator, come here!” Because there’s absolutely no need for hostility. People are only trying their best to contribute to YOUR project.

**Comment by leezhiwei** [comment]
Hi @BroGamer4256, would like to ask if there is any suggestions for me to rewrite the code? Like for example a specific function for me to hook onto and such, if you find the existing one inappropriate. Thanks.

**Pull request closed without merging**
