### PR TITLE
fix controller drifting + remove assert on openal

### PR DESCRIPTION
**Pull request by feathercx**

### CODE REVIEW

**Comment by BroGamer4256** [comment]
The "controller drift" fix won't work as intended and the assert is intentional, it should panic if those values are equal.

**Comment by BroGamer4256** [comment]
If you are having issues with controller drift I suggest increasing the deadzone, I have implemented a fix for fast flicks loosely based on your commit with #a273836

**Comment by feathercx** [comment]
image

the assert always trips for me (pop os)

also by controller drift i meant fast flicks, my bad..

**Comment by BroGamer4256** [comment]
This likely means you either don't have my libopenal.so built to work with the game, or aren't using the provided start script that makes sure it can be found by ld and preloads it.

**Comment by feathercx** [comment]
removing libopenal.so fixes it

**Pull request closed without merging**
