### PR TITLE
Hook clSerialN2::open to allow for non-serial tty's

### PR DESCRIPTION
**Pull request by GXTX**
This does kill normal serial tty's in it's current state, but it wouldn't be too difficult to add back that functionality.

Test if the tty was able to be open as serial, if not fallback to what I've proposed here.

### CODE REVIEW

**Comment by BroGamer4256** [comment]
This code is incredibly dirty with a lot of needless repetition. Clean it up.

**Comment by GXTX** [comment]
That comment provides zero indication as to what you'd like to see changed.

**Comment by BroGamer4256** [comment]
I believe its perfectly clear, clean the code and remove all unnecessary duplication. There's not much to indicate towards given how small the changes are.

**Comment by GXTX** [comment]
> all unnecessary duplication

*What* unnecessary duplication.

**Pull request closed without merging**
